#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# Add user's python package path to be safe in the app environment
export PYTHONPATH="/Users/hedamao/Library/Python/3.9/lib/python/site-packages:$PYTHONPATH"
/usr/bin/python3 "$DIR/FloatingTask.py"
